package io.github.brainage04.fabricmoddingconventions.gradle.multiloader;

import org.gradle.api.DefaultTask;
import org.gradle.api.file.DirectoryProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.Input;
import org.gradle.api.tasks.OutputDirectory;
import org.gradle.api.tasks.TaskAction;
import org.gradle.work.DisableCachingByDefault;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Generates the NeoForge {@code gametest} source set's GameTest ticker. A production NeoForge server never ticks
 * GameTests (NeoForge's {@code GameTestHooks.isGametestEnabled()} is false in production), so a production GameTest
 * server would start its tests and wait for them forever. The generated subscriber ticks them on the GameTest
 * server whenever NeoForge does not; in development NeoForge ticks them itself and the subscriber does nothing.
 */
@DisableCachingByDefault(because = "Writes one small source file; caching costs more than regenerating it")
public abstract class GenerateProductionGameTestTickerTask extends DefaultTask {
    static final String PACKAGE = "io.github.brainage04.fabricmoddingconventions.neoforge.gametest";
    static final String CLASS_NAME = "ProductionGameTestTicker";

    public GenerateProductionGameTestTickerTask() {
        setDescription("Generates the subscriber that ticks GameTests on a production NeoForge GameTest server.");
    }

    @Input
    public abstract Property<String> getModId();

    @OutputDirectory
    public abstract DirectoryProperty getOutputDirectory();

    @TaskAction
    public void generate() throws IOException {
        Path target = getOutputDirectory().get().getAsFile().toPath()
                .resolve(PACKAGE.replace('.', '/'))
                .resolve(CLASS_NAME + ".java");
        Files.createDirectories(target.getParent());
        Files.writeString(target, """
                package %s;

                import net.minecraft.gametest.framework.GameTestServer;
                import net.minecraft.gametest.framework.GameTestTicker;
                import net.minecraft.server.MinecraftServer;
                import net.neoforged.bus.api.SubscribeEvent;
                import net.neoforged.fml.common.EventBusSubscriber;
                import net.neoforged.neoforge.event.tick.ServerTickEvent;
                import net.neoforged.neoforge.gametest.GameTestHooks;

                /**
                 * Generated by io.github.brainage04.multiloader-mod-conventions. NeoForge only ticks GameTests outside
                 * production, so on a production GameTest server this ticks them the way MinecraftServer does in
                 * development. Wherever NeoForge ticks them itself, this does nothing.
                 */
                @EventBusSubscriber(modid = "%s")
                public final class %s {
                    private %s() {
                    }

                    @SubscribeEvent
                    public static void tickGameTests(ServerTickEvent.Post event) {
                        MinecraftServer server = event.getServer();
                        if (server instanceof GameTestServer
                                && !GameTestHooks.isGametestEnabled()
                                && server.tickRateManager().runsNormally()) {
                            GameTestTicker.SINGLETON.tick();
                        }
                    }
                }
                """.formatted(PACKAGE, getModId().get(), CLASS_NAME, CLASS_NAME));
    }
}
